create extension if not exists pgcrypto;

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'user',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_devices (
  id bigint generated by default as identity primary key,
  device_token_hash text not null unique,
  device_name text null,
  browser_info text null,
  ip_address text null,
  status text not null default 'pending',
  approved_by text null,
  approved_at timestamptz null,
  last_seen_at timestamptz null,
  created_at timestamptz not null default now()
);

alter table public.app_devices add column if not exists device_token_hash text;
alter table public.app_devices add column if not exists device_name text;
alter table public.app_devices add column if not exists browser_info text;
alter table public.app_devices add column if not exists ip_address text;
alter table public.app_devices add column if not exists status text not null default 'pending';
alter table public.app_devices add column if not exists approved_by text;
alter table public.app_devices add column if not exists approved_at timestamptz;
alter table public.app_devices add column if not exists last_seen_at timestamptz;
alter table public.app_devices add column if not exists created_at timestamptz not null default now();

create unique index if not exists app_devices_device_token_hash_idx
  on public.app_devices(device_token_hash);

create table if not exists public.wa_business_accounts (
  id bigint generated by default as identity primary key,
  waba_id text not null unique,
  name text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wa_phone_numbers (
  id bigint generated by default as identity primary key,
  business_account_id bigint not null references public.wa_business_accounts(id) on delete cascade,
  display_name text not null,
  phone_number text not null,
  phone_number_id text not null unique,
  access_token text not null,
  verify_token text not null,
  api_version text not null default 'v22.0',
  webhook_path text null,
  is_default boolean not null default false,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wa_contacts (
  id bigint generated by default as identity primary key,
  wa_id text not null unique,
  phone_number text null,
  profile_name text null,
  business_directory_name text null,
  notes text null,
  opt_in_status text not null default 'unknown',
  opt_in_keyword text null,
  opt_in_source text null,
  opt_in_updated_at timestamptz null,
  last_opt_in_template_name text null,
  last_opt_in_prompt_at timestamptz null,
  last_inbound_at timestamptz null,
  last_outbound_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wa_conversations (
  id bigint generated by default as identity primary key,
  phone_number_id bigint not null references public.wa_phone_numbers(id) on delete cascade,
  contact_id bigint not null references public.wa_contacts(id) on delete cascade,
  last_message_id bigint null,
  last_message_preview text null,
  last_message_at timestamptz null,
  unread_count integer not null default 0,
  is_archived boolean not null default false,
  cleared_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (phone_number_id, contact_id)
);

create table if not exists public.wa_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.wa_conversations(id) on delete cascade,
  phone_number_id bigint not null references public.wa_phone_numbers(id) on delete cascade,
  contact_id bigint not null references public.wa_contacts(id) on delete cascade,
  direction text not null,
  message_type text not null,
  wa_message_id text null unique,
  parent_wa_message_id text null,
  text_body text null,
  caption text null,
  media_id text null,
  media_url text null,
  mime_type text null,
  file_name text null,
  template_name text null,
  template_language text null,
  template_params jsonb null,
  campaign_id bigint null,
  status text not null default 'queued',
  error_message text null,
  wa_timestamp timestamptz null,
  sent_at timestamptz null,
  delivered_at timestamptz null,
  read_at timestamptz null,
  failed_at timestamptz null,
  starred_at timestamptz null,
  deleted_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wa_templates (
  id bigint generated by default as identity primary key,
  phone_number_id bigint null references public.wa_phone_numbers(id) on delete cascade,
  template_name text not null,
  category text null,
  language text not null,
  status text null,
  header_format text null,
  body_text text null,
  footer_text text null,
  buttons_json jsonb null default '[]'::jsonb,
  meta_template_id text null,
  last_synced_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wa_contact_lists (
  id bigint generated by default as identity primary key,
  phone_number_id bigint not null references public.wa_phone_numbers(id) on delete cascade,
  name text not null,
  source text not null default 'manual',
  is_archived boolean not null default false,
  cleared_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wa_contact_list_members (
  id bigint generated by default as identity primary key,
  list_id bigint not null references public.wa_contact_lists(id) on delete cascade,
  contact_id bigint not null references public.wa_contacts(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (list_id, contact_id)
);

create table if not exists public.wa_campaigns (
  id bigint generated by default as identity primary key,
  phone_number_id bigint not null references public.wa_phone_numbers(id) on delete cascade,
  contact_list_id bigint null references public.wa_contact_lists(id) on delete set null,
  title text not null,
  mode text not null,
  body_text text null,
  media_id text null,
  mime_type text null,
  file_name text null,
  template_name text null,
  initial_template_name text null,
  followup_template_name text null,
  template_language text null,
  template_params_json jsonb null default '[]'::jsonb,
  status text not null default 'pending',
  total_recipients integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz null,
  completed_at timestamptz null
);

create table if not exists public.wa_campaign_recipients (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.wa_campaigns(id) on delete cascade,
  recipient_wa_id text not null,
  recipient_name text null,
  contact_list_member_id bigint null references public.wa_contact_list_members(id) on delete set null,
  contact_id bigint null references public.wa_contacts(id) on delete set null,
  conversation_id bigint null references public.wa_conversations(id) on delete set null,
  wa_message_id text null,
  pending_text_body text null,
  prompt_template_name text null,
  status text not null default 'queued',
  error_message text null,
  opt_in_requested_at timestamptz null,
  opted_in_at timestamptz null,
  sent_at timestamptz null,
  delivered_at timestamptz null,
  read_at timestamptz null,
  failed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.wa_messages add column if not exists starred_at timestamptz null;
alter table public.wa_messages add column if not exists deleted_at timestamptz null;
alter table public.wa_campaigns add column if not exists media_id text null;
alter table public.wa_campaigns add column if not exists mime_type text null;
alter table public.wa_campaigns add column if not exists file_name text null;

create index if not exists idx_wa_contacts_profile_name on public.wa_contacts using btree (profile_name);
create index if not exists idx_wa_contacts_phone_number on public.wa_contacts using btree (phone_number);
create index if not exists idx_wa_contacts_opt_in_status on public.wa_contacts using btree (opt_in_status, last_inbound_at desc);
create index if not exists idx_wa_conversations_last_message_at on public.wa_conversations using btree (last_message_at desc, id desc);
create index if not exists idx_wa_conversations_phone_number_id on public.wa_conversations using btree (phone_number_id, last_message_at desc, id desc);
create index if not exists idx_wa_messages_conversation_created on public.wa_messages using btree (conversation_id, created_at desc, id desc);
create index if not exists idx_wa_messages_wa_message_id on public.wa_messages using btree (wa_message_id);
create index if not exists idx_wa_messages_starred_at on public.wa_messages using btree (starred_at desc) where starred_at is not null;
create index if not exists idx_wa_contact_lists_phone_number_id on public.wa_contact_lists using btree (phone_number_id, created_at desc);
create index if not exists idx_wa_contact_list_members_list_id on public.wa_contact_list_members using btree (list_id, position, id);
create index if not exists idx_wa_campaigns_status_created on public.wa_campaigns using btree (status, created_at desc);
create index if not exists idx_wa_campaign_recipients_campaign_status on public.wa_campaign_recipients using btree (campaign_id, status, id);

alter table public.wa_contacts add column if not exists business_directory_name text null;
alter table public.wa_contacts add column if not exists opt_in_status text not null default 'unknown';
alter table public.wa_contacts add column if not exists opt_in_keyword text null;
alter table public.wa_contacts add column if not exists opt_in_source text null;
alter table public.wa_contacts add column if not exists opt_in_updated_at timestamptz null;
alter table public.wa_contacts add column if not exists last_opt_in_template_name text null;
alter table public.wa_contacts add column if not exists last_opt_in_prompt_at timestamptz null;
alter table public.wa_conversations add column if not exists cleared_at timestamptz null;
alter table public.wa_conversations add column if not exists is_archived boolean not null default false;
alter table public.wa_contact_lists add column if not exists is_archived boolean not null default false;
alter table public.wa_contact_lists add column if not exists cleared_at timestamptz null;
alter table public.wa_campaigns add column if not exists contact_list_id bigint null references public.wa_contact_lists(id) on delete set null;
alter table public.wa_campaigns add column if not exists initial_template_name text null;
alter table public.wa_campaigns add column if not exists followup_template_name text null;
alter table public.wa_campaign_recipients add column if not exists contact_list_member_id bigint null references public.wa_contact_list_members(id) on delete set null;
alter table public.wa_campaign_recipients add column if not exists pending_text_body text null;
alter table public.wa_campaign_recipients add column if not exists prompt_template_name text null;
alter table public.wa_campaign_recipients add column if not exists opt_in_requested_at timestamptz null;
alter table public.wa_campaign_recipients add column if not exists opted_in_at timestamptz null;

create index if not exists idx_wa_messages_deleted_at on public.wa_messages using btree (deleted_at) where deleted_at is not null;

alter table public.wa_business_accounts disable row level security;
alter table public.wa_phone_numbers disable row level security;
alter table public.wa_contacts disable row level security;
alter table public.wa_conversations disable row level security;
alter table public.wa_messages disable row level security;
alter table public.wa_templates disable row level security;
alter table public.wa_contact_lists disable row level security;
alter table public.wa_contact_list_members disable row level security;
alter table public.wa_campaigns disable row level security;
alter table public.wa_campaign_recipients disable row level security;
